name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Print environment variables
        run: env

      - name: Ninja version
        run: version --version
