# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  clang_version: 13

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install CMake
      uses: ssrobins/install-cmake@main

    - name: Install Conan
      run: pip3 install conan --pre --upgrade

    - name: Install required macOS packages
      run: brew install ninja

    - name: Build and install Include what you use
      run: |
        brew install llvm@${{ env.clang_version }}
        git clone https://github.com/include-what-you-use/include-what-you-use.git
        cd include-what-you-use
        git checkout clang_${{ env.clang_version }}
        cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=$(brew --prefix llvm@${{ env.clang_version }})/bin/clang -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@${{ env.clang_version }})/bin/clang++ -DCMAKE_PREFIX_PATH=$(brew --prefix llvm@${{ env.clang_version }})/lib/cmake -B build
        cmake --build build --config Release --parallel
        echo "$RUNNER_WORKSPACE/include-what-you-use/build/bin/include-what-you-use" >> $GITHUB_PATH

    - name: Use Include what you use
      run: |
        git clone https://github.com/ssrobins/stackblox
        cd stackblox
        git checkout setup_iwyu
        ./cmake.py macos --iwyu
