name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, windows-2022, windows-2019, macos-12, macos-11, macos-10.15]
    steps:
      - uses: actions/checkout@v3

      - name: Print environment variables
        run: env

      - name: Python version
        run: python3 --version

      - name: Print pip cache
        run: python3 -m pip cache dir
