name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
    steps:
      - uses: actions/checkout@v3

      - name: Print environment variables
        run: env

      - name: CMake configure
        run: cmake -G "Visual Studio 17 2022" -B build

      - name: Install Conan
        run: |
          pip3 install conan --upgrade
          conan profile detect

      - name: Conan install
        run: conan install . --build=missing -s os=Windows -s compiler=msvc -s compiler.version=193 -s compiler.update=6
