name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, windows-2022, windows-2019, macos-12, macos-11, macos-10.15]
    steps:
      - uses: actions/checkout@v3

      - name: Print environment variables
        run: env

      - name: Install Conan
        run: |
          pip3 install conan --pre --upgrade
          pip3 show conan

      - name: which Conan
        run: which conan
        continue-on-error: true

      - name: where Conan
        run: where conan
        continue-on-error: true
