name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:
      - uses: actions/checkout@v3

      - name: Install Conan
        run: |
          pip3 install conan --upgrade
          conan profile detect

      - name: Print compiler dir contents
        run: Get-ChildItem -Path "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.36.32532/bin/Hostx64" -Recurse

      - name: Conan install
        run: conan install --requires=fmt/9.1.0 --build=missing -s compiler=msvc -s compiler.version=193

      - name: Conan install compiler.update=6
        run: conan install --requires=fmt/9.1.0 --build=missing -s compiler=msvc -s compiler.version=193 -s compiler.update=6
