# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Print environment variables
      run: env
    
    - name: Install CMake
      run: |
        $cmake_version = "3.19.0-rc1"
        $cmake_dir = "cmake-${cmake_version}-win64-x64"
        $cmake_zip = "${cmake_dir}.zip"
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest https://github.com/Kitware/CMake/releases/download/v${cmake_version}/${cmake_zip} -outFile ${cmake_zip}
        Expand-Archive -Path $cmake_zip
        dir ${Env:GITHUB_WORKSPACE}/${cmake_dir}
        echo "${Env:GITHUB_WORKSPACE}/${cmake_dir}/bin" >> ${Env:GITHUB_PATH}

    - name: Print environment variables
      run: env

    - name: CMake version
      run: cmake --version
        
