name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2019]
    steps:
      - uses: actions/checkout@v3

      - name: CMake project generation
        run: cmake -A Win32 -B build

      - name: Build
        run: cmake --build build