# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  builds:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macos-11
            os: macos-11
          - name: macos-12
            os: macos-12
    steps:
    - name: env
      run: env

    - name: Install Conan
      run: pip3 install conan --pre --upgrade

    - name: pip show
      run: pip3 show conan

    - name: list pythons
      run: ls -lR /Library/Frameworks/Python.framework/Versions

    - name: Set python
      run: echo "/Library/Frameworks/Python.framework/Versions/3.11" >> $GITHUB_PATH

    - name: conan version
      run: conan --version
